name: digital_eye_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^2.3.2+1
  provider: ^4.3.2+2
  random_string: ^2.0.1
  intro_slider: ^2.3.3
  flutter_timetable_view: ^0.1.0
  image: ^2.1.18
  circular_check_box: any
  image_picker: ^0.6.7+12
  firebase_messaging: ^7.0.0
  animator: ^2.0.1
  global_configuration:
  modal_progress_hud:
  date_util: any
  gradient_widgets: any
  page_indicator: any
  flutter_inner_drawer: any
  carousel_slider: any
  flutter_calendar_carousel: any
  smooth_star_rating: any
  table_calendar: ^2.2.3
  syncfusion_flutter_charts: ^18.3.38
  percent_indicator: ^2.1.7+4
  auto_size_text: 2.1.0
  flutter_ringtone_player: 2.0.0
  progress_indicators: ^0.1.5
  
  camera: ^0.5.8+17
  flutter_local_notifications: ^3.0.1+5
  image_crop: ^0.3.4
  extended_image: ^1.2.0
  flutter_native_image: ^0.0.5+3
  syncfusion_flutter_gauges: ^18.2.44
  redux: ^4.0.0+3
  flutter_redux: ^0.7.0
  key_value_store_flutter:
  rxdart: ^0.24.1
  redux_persist: ^0.8.4
  path_provider: ^1.6.24
  intl: ^0.16.1
  shared_preferences:
  flutter_native_timezone: ^1.0.4
  device_info: ^1.0.0
  firebase_auth: ^0.18.4
  cupertino_icons: ^0.1.3
  flutter_svg:
  preview: ^0.0.8
  firebase_ml_vision: ^0.9.9
  firebase_core: ^0.5.2+1
  cloud_firestore: ^0.14.3+1
  firebase_storage: ^5.1.0
  simple_animations: ^1.1.3
  page_transition: ^1.1.4


  






 






  



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - Assets/Blogs/one.png
    - Assets/Blogs/scanner.png
    - Assets/Blogs/logo.png
    - Assets/images/
    - Assets/Onboarding/appointment.png
    - Assets/Onboarding/doctor.png
    - Assets/Onboarding/medication.png
    - Assets/DoctorList/doctor1.jpg
    - Assets/DoctorList/doctor2.jpg
    - Assets/DoctorList/doctor3.png
    - Assets/DoctorList/doctor4.png
    - Assets/DoctorList/doctor5.png
    - Assets/DoctorList/doctor6.png
    - Assets/DoctorList/doctor7.png
    - Assets/DoctorList/doctor8.png
    - Assets/Hospital/hospital1.png
    - Assets/DrugsList/drugImage.png
    - Assets/Login/Logo.png
    - Assets/Login/eye.jpg
    - Assets/DoctorProfile/message.png
    - Assets/DoctorProfile/phone.png
    - Assets/DoctorProfile/doctor.png
    - Assets/DoctorProfile/closed.jpg
    - Assets/DoctorProfile/profileDoctor.jpeg
    - Assets/Language/localization_en.json
    - Assets/Language/localization_fr.json
    - Assets/Language/localization_es.json
    - Assets/Language/localization_ar.json
    - Assets/Checkout/Card.png
    - Assets/Checkout/Cod.png
    - Assets/Checkout/success.png
    - Assets/Checkout/paypal.png
    - Assets/Blogs/food.jpeg
    #  - images/a_dot_ham.jpeg



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
